variables:
  PHP_IMAGE: "gitlab.lan.bauer-kirch.de:5001/eap/php/docker/php:php-8.1"
  SYMFONY_PHPUNIT_DIR: "vendor/bin/.phpunit"

setup_php:
  stage: setup
  tags:
    - docker
  image: $PHP_IMAGE
  script:
    - time composer install
  cache:
    key:
      files:
        - composer.lock
    paths:
      - vendor
  artifacts:
    expire_in: 30m
    paths:
      - vendor

linting_php:
  stage: test
  tags:
    - docker
  image: $PHP_IMAGE
  script:
    - time vendor/bin/phpstan analyse -c phpstan.neon

linting_twig:
  stage: test
  tags:
    - docker
  image: $PHP_IMAGE
  script:
    - time php bin/console lint:twig templates

unit_tests_php:
  stage: test
  tags:
    - docker
  image: $PHP_IMAGE
  script:
    - time php bin/phpunit --log-junit phpunit-log.xml
  artifacts:
    when: always
    paths:
      - phpunit-log.xml
    reports:
      junit: phpunit-log.xml

audit_depdash:
  stage: audit
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  tags:
    - depdash
  script:
    - /opt/bauer-kirch/depdash-composer-client/bin/console composer:report --gitlab
    - /opt/bauer-kirch/depdash-composer-client/bin/console composer:security-report
  allow_failure: true
