#!/usr/bin/env bash

# Paths and configuration
BASEDIR="$(cd "$(dirname "$0")/.." && pwd)"
CERTS_DIR=$BASEDIR/var/certs

# Create certificate using nginx image
mkdir -p $CERTS_DIR
docker run \
  --rm \
  --entrypoint openssl \
  -v $CERTS_DIR:/var/www/certs \
  -w /var/www/certs \
  nginx:latest \
  req -newkey rsa:4096 \
    -x509 \
    -sha256 \
    -days 365 \
    -nodes \
    -subj "/CN=localhost" \
    -out app-cert.pem \
    -keyout app-key.pem