#!/usr/bin/env bash

# Paths and configuration
BASEDIR="$(cd "$(dirname "$0")/.." && pwd)"
DOT_ENV=$BASEDIR/.env

# Load Env files
test -f $DOT_ENV && source $DOT_ENV

if [ "$1" = "open" ]; then
  UI_ARGUMENTS="--env DISPLAY \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket"
else
  UI_ARGUMENTS=""
fi

CYPRESS_ARGUMENTS="${@:2}"

# install dependencies
docker run \
  --workdir /var/www/app \
  --env-file $DOT_ENV \
  --env NPM_CONFIG_CACHE=/var/www/app/var/volumes/.npm \
  --rm \
  -v $BASEDIR/app:/var/www/app \
  node:12 \
  bash -c "time npm install"

# automatically runs as root; the created files (cypress/screenshots & cypress/videos) therefore belong to root
# needs to be updated later in job's after_script
docker run \
  --ipc=host \
  --network ${CI_PROJECT_NAME}_default \
  --workdir /var/www/app \
  --env-file $DOT_ENV \
  --env CYPRESS_BASE_URL=https://nginx \
  --rm \
  --entrypoint cypress \
  -v $BASEDIR/app:/var/www/app \
  -v $BASEDIR/var/volumes/.npm:/root/.npm \
  $UI_ARGUMENTS \
  cypress/included:5.2.0 \
  $1 --project /var/www/app $CYPRESS_ARGUMENTS
